using System.Runtime.Serialization;

namespace DataLayer
{
    [DataContract]
    public class GameServerData
    {
        #region Properties

        /// <summary>
        /// The displayed name of the server (given by the user that created the server)
        /// </summary>
        [DataMember]
        public string Name { get; set; }

        /// <summary>
        /// Used for joining the server (identifing as a valid user).
        /// This is generated by the server
        /// </summary>
        public string Identifier { get; set; }

        /// <summary>
        /// The password of the game server. Will be null or empty if no password is provided
        /// </summary>
        public string Password { get; set; }

        /// <summary>
        /// Indicates whetere there is a password
        /// </summary>
        [DataMember]
        public bool HasPassword { get => !string.IsNullOrEmpty(Password); }
        
        /// <summary>
        /// The port of the hosting  server
        /// </summary>
        [DataMember]
        public ushort Port { get; set; }

        /// <summary>
        /// The ip of the hosting server
        /// </summary>
        [DataMember]
        public string Ip { get; set; }

        #endregion
    }
}